var strings = {
    "Author": "作者",
    "Title": "标题",
    "Co-Author": "合作者",
    "Search": "搜索",
    "Home Page": "主页",
    "Author(s)": "作者",
    "Year": "年份",
    "Modified": "修改日期",
    "Co-Author(s)": "合作者",
    "coauthor": "合作者",
    "author": "作者",
    " not found!": "未找到！",
    "authors": "作者",
    "ee": "链接",
    "journal": "期刊",
    "key": "关键码",
    "mdate": "修改日期",
    "number": "编号",
    "pages": "页码",
    "title": "标题",
    "url": "网址",
    "volume": "卷",
    "year": "年份",
    "booktitle": "书名",
    "series": "系列",
    "note": "备注",
    "address": "位置",
    "month": "月份",
    "cdrom": "光盘",
    "publisher": "出版社",
    "crossref": "引用",
    "isbn": "ISBN",
    "school": "学校",
    "chapter": "章节",
    "You can not search this title.": "无法搜索此标题。"
};