var strings = {
    "authors": "Authors",
    "ee": "Link",
    "journal": "Journal",
    "key": "Key",
    "mdate": "Modified",
    "number": "Number",
    "pages": "Pages",
    "title": "Title",
    "url": "URL",
    "volume": "Volume",
    "year": "Year",
    "booktitle": "Booktitle",
    "series": "Series",
    "note": "Note",
    "address": "address",
    "month": "Month",
    "cdrom": "CD-ROM",
    "publisher": "Publisher",
    "crossref": "Crossref",
    "isbn": "ISBN",
    "school": "School",
    "chapter": "Chapter",
};