name: CI
on:
  push:
    branches:
    - master
    paths-ignore:
    - '.github/workflows/Test.yml'
    tags-ignore:
    - 'v*'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/cache@v2
        id: cache-qt
        with:
          path: ../Qt
          key: ${{ runner.os }}/Qt/5.15.0
      - uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.0
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - uses: actions/checkout@v2
      - name: msvc build
        shell: cmd
        run: build ci
      - name: cache dblp data
        id: cache-dblp
        uses: actions/cache@v2
        with:
          path: dblp-2020-05-01.xml
          key: ${{ runner.os }}/dblp-2020-05-01.xml
      - uses: actions/setup-python@v2
        if: steps.cache-dblp.outputs.cache-hit != 'true'
      - uses: actions/checkout@v2
        if: steps.cache-dblp.outputs.cache-hit != 'true'
      - name: setup dblp data
        if: steps.cache-dblp.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          pip3 install requests
          pip3 install clint
          python .\download.py
          7z x dblp-2020-05-01.xml.gz
      - name: run test
        shell: cmd
        run: dblp dblp-2020-05-01.xml